# Generated by Django 3.0.3 on 2020-03-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20200303_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Temphum',
        ),
    ]
