# Generated by Django 3.0.3 on 2020-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_auto_20200303_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temphum',
        ),
    ]
